### ISSUE TITLE
Good to note: Unknown6 is also used for transferring items available to purchase

### ISSUE THREAD

**Issue by tjhorner** [pkmngodev/Unknown6#16]
It's also used for requesting and sending IAPs, more info can be found at my PR: AeonLucid/POGOProtos#98

**Comment by christosk92** [comment]
I really don't think this will be a good idea, this is even worse than botting. But after all Niantic fucked it up for themselves, when they activated Unkown6. They really should have just created private api keys for developers

**Comment by tjhorner** [comment]
@christosk92 I don't think we'll be able to actually use this-- this is just for giving info to the play store or app store on what IAP ID to send.

**Comment by christosk92** [comment]
@tjhorner  I really hope so

**Comment by nullpixel1** [comment]
Hi, this is really nice, so I'm going to close and mark it as Archived so we can come back to it later.

**Comment by MaxLeiter** [comment]
Actually I think we should leave it open for people to see and discuss, @nullpixel1 @RocketRaccoon7

**Comment by nullpixel1** [comment]
Your call @MaxLeiter

**Comment by tjhorner** [comment]
>Actually I think we should leave it open for people to see and discuss

So should I mute my notifications or... :laughing:

**Comment by tjhorner** [comment]
So here are the files I've gathered from that PR that will definitely be useful:

- https://github.com/tjhorner/POGOProtos/blob/6b15a83e7d9a03c9d97c26d3f34f4e059a153330/src/POGOProtos/Networking/Envelopes/Unknown6Response.proto
- https://github.com/tjhorner/POGOProtos/blob/6b15a83e7d9a03c9d97c26d3f34f4e059a153330/src/POGOProtos/Networking/Envelopes/ResponseEnvelope.proto
