### ISSUE TITLE
Encryption may Aes256?

### ISSUE THREAD

**Issue by Lasertrap00** [pkmngodev/Unknown6#28]
Is it possible that its encrypted with aes256? Because the pseudo c code looks a bit similar to aes256 encryption

**Comment by Lasertrap00** [comment]
And could u add me to the chat?

**Comment by Roenbaeck** [comment]
It looks more like NTRU (https://godoc.org/github.com/Yawning/ntru) to me.

**Comment by Lasertrap00** [comment]
The header is may be the key / iv

**Comment by nullpixel1** [comment]
We've already looked into the possibility that it is encrypted with AES256, and it isn't.

For a start the header isn't the key.

Nice suggestion though.

**Comment by Lasertrap00** [comment]
The guy is reading the chat

**Comment by nullpixel1** [comment]
I know. :)

**Comment by Lasertrap00** [comment]
No xD
Could u give me Talk perm

**Comment by nullpixel1** [comment]
Sorry. We're quite full.
