### ISSUE TITLE
sub_9E9D8_decrypt() is illogical

### ISSUE THREAD

**Issue by rryles** [pkmngodev/Unknown6#34]
I realise it's a quick and dirty attempt to reverse the encryption, but it doesn't make sense.

It ends with
```c
    sub_87568((unsigned char*)temp, (unsigned char*)temp2);
	memcpy(output, temp2, 0x100);
```
however sub_87568 produces it's output in temp, not temp2.  What is needed is the inverse of sub_87568. (It is not self inverse)

**Comment by globeriz** [comment]
source? I don't think anyone has came up with a decrypt function yet

**Comment by rryles** [comment]
https://github.com/pkmngodev/Unknown6/blob/master/c_code/encrypt.c

**Comment by globeriz** [comment]
Acknowledged, submitting PR soon
