### ISSUE TITLE
Cloudflare or Discord fucked up

### ISSUE THREAD

**Issue by shark0der** [pkmngodev/Unknown6#40]
![image](https://cloud.githubusercontent.com/assets/528959/17441005/c6400b32-5b37-11e6-804a-192dc8693c69.png)

(same response from 8.8.8.8)

**Comment by ur0** [comment]
It's back for me.

**Comment by gnought** [comment]
Not "host discordapp.com" ?

**Comment by shark0der** [comment]
@gnought the websocket connection is failing, as seen in chrome's console

**Comment by nullpixel1** [comment]
Closed as this issue isn't related to UK 6. You can of course continue to discuss this.

**Comment by gnought** [comment]
It seems it's back again.

**Comment by shark0der** [comment]
Google/Cloudflare still returning 127.0.0.1 for me. Even if I `dig` from different locations.

**Comment by shark0der** [comment]
Can someone give me the IP for `discordapp.io` so I can try putting it in hosts?

**Comment by shark0der** [comment]
It's back up.

**Comment by ur0** [comment]
Am still having issues. Apologies everyone who's trying to reach me.

**Comment by shark0der** [comment]
Offline (again) for me as well.
