### ISSUE TITLE
Source Code

### ISSUE THREAD

**Issue by makertech81** [pkmngodev/Unknown6#44]
How useful is having the source code of PoGo?  I don't know if this has been accomplished yet, but I have found everything including the classes and server keys used in PoGo.

Just Trying to help!

Maker

**Comment by shark0der** [comment]
https://github.com/pkmngodev/Unknown6/issues/5#issuecomment-237754201

**Comment by makertech81** [comment]
Ok, thanks.  Sorry!

**Comment by shark0der** [comment]
Close the issue please.

**Comment by Abraxas000** [comment]
If you legitimately have the source code somehow and not just the compiled app, feel free to PM a link to me and I'll verify it.
