### ISSUE TITLE
Can Niantic Stop the Encryption Being Cracked?

### ISSUE THREAD

**Issue by lufthansa747** [pkmngodev/Unknown6#50]
From my understanding the first main hurtle to solving the unknown6 problem was cracking the encryption used for the proto parameters. The encryption was cracked by tracking down the key stored in the APK(this is my best guess at how it was cracked). After the encryption was cracked work could begin on reverse engineering the encrypted parameters in order to understand what they are and how to reproduce them. (please correct me if my understanding of something is wrong)

Did Niantic make a mistake in how they implemented the encryption? or will any attempt of encryption be vulnerable to being cracked by dedicated devs?

**Comment by xssc** [comment]
We can always find the inputs, it just may get harder and harder. The client must be able to know what it needs to send. Then we can find what it sends and try to spoof it

**Comment by mlthomas** [comment]
No, they did not. It is not correct to say the encryption was cracked. That implies that after encrypting, one could decrypt. In assymetrical cryptography, you encrypt with one side and decrypt with the other. If you cannot decrypt then you do not understand the structure being encrypted. It is the nature or shape of the input data being encrypted that was reversed-engineered so it could be replicated and encrypted with the same key and will correctly be decrypted and recognized on the server side.  It is true that this process could easily occur again, but that would required pushing a new client to distribute new native code-based logic and even new keys to use. So every client update could theoretically force a repeat. Hopefully the lessons learned would make this repeated process faster.

**Comment by wchill** [comment]
GitHub issues is not a forum. Please take questions to Discord or reddit.
