### ISSUE TITLE
Technical Update So Far.

### ISSUE THREAD

**Issue by keyphact** [pkmngodev/Unknown6#65]
**Detailed info for those who are interested:**
The new struct, which we are calling `Signature` (previously `Unknown6`), authenticates every request made to the API. The structure of `Signature` turns out to be made up of a few more structures and values. We've managed to figure out what some of those are, leaving only a few remaining.

The integer `unknown_10` is a hash generated by Pokémon Go. It is made by taking the user's current authentication ticket in protobuf format (app specific; different from their PTC or Google login token) and running it through a hashing function called `xxHash32`.
While our understanding of `xxHash32` is not complete, from what we know, this hash function takes three values: the first being some data to hash, the second being a 32-bit integer to use as a "seed value" to start the function with, and the third being how many bytes from the data to use for hashing. In this case, the seed value has been determined to be `0x1B845328`. This spits out a new 32-bit integer.

Now we take this integer and use it as the seed value to hash our current latitude, longitude, and altitude. The resulting 32-bit integer is `unknown_10`.

Similarly, the integer `unknown_20` is another hash generated by the game. We take the current latitude, longitude, and altitude, as before, and hash it once again using `xxHash32`, with `0x1B845238` as the seed value. The resulting 32-bit integer is `unknown_20`.

We're not 100% sure about how to generate `unknown_22`, but it acts as a check to prevent users from simply copy-pasting API requests from the app. In other words, it prevents replay attacks. `unknown_22` is time based and changes every few minutes.

Finally, `unknown_24` (now known as `request_hash`) is an array of hashes, one for each function call being called via the API. (So, for example, getting the player info and inventory list in the same API call would result in two hashes.)
To generate `request_hash`, we start by hashing the authentication ticket with a seed value of `0x1B45328`, but this time using the hashing function `xxHash64`. This becomes our new seed value for the remaining hashes.

Now, for each RPC function call included in the request, we take its protobuf data and hash using `xxHash64` using the `xxHash64` hash of the authentication ticket. The set of all these hashes is our `request_hash`.

**Comment by thelostcode** [comment]
Good summary!

**Comment by JoorgeFerrari** [comment]
You guys rock!

**Comment by AhmadS12** [comment]
Good to hear!

**Comment by HaydarOzturk** [comment]
is that mean API works now?

**Comment by IstenesImre** [comment]
<3

**Comment by ddrght12345** [comment]
Awesome! Glad you guys are making so much progress on this.

**Comment by famofa24** [comment]
API work?

**Comment by InvisibleTouch** [comment]
Great Job....

**Comment by HasanY1989** [comment]
You guys rock !

**Comment by Midnlght** [comment]
What a time to be alive lol

**Comment by rbryson74** [comment]
That summary is gorgeous.

**Comment by thappy** [comment]
Amazing. How do I buy you coffee

**Comment by xXDarkBladeXx** [comment]
nice 1

**Comment by Devphex** [comment]
Awesome!! Good job developers

**Comment by pet90210** [comment]
no API doesn't work .. for gods sake. READ the post and when you don't understand the technical things he is talking about look here ... https://www.reddit.com/live/xdkgkncepvcq

**Comment by thisisritz** [comment]
Amazing job, thanks Debuggers!

**Comment by CyberChrist777** [comment]
I sense more beer money on the way...

**Comment by codman96** [comment]
so can yous fix it?

**Comment by J-rooft** [comment]
Yau are awesome!

**Comment by Dejamelofiao** [comment]
WE CAN GUYS!!

**Comment by BobbyWibowo** [comment]
Sounds epic.

**Comment by yeuna** [comment]
I LOVE YOU GUYS! FEELSGOODMAN

**Comment by DestroyerJoules** [comment]
Nice work guys !! When the bot will be up +/- in ur prespective? Continue with ur job :)

**Comment by HasanY1989** [comment]
Stop asking questions that been answered, and for once read what the devs write. 
NO the API is not working yet, however they in good progress,  a request generator is working, but they fare from done...

**Comment by DestroyerJoules** [comment]
Great job

**Comment by DestroyerJoules** [comment]
Great job continue with ur work!! In ur prespective when the bots will be up? Thanks and donated :)

**Comment by BobbyWibowo** [comment]
Also please note that the dev team is not only made up by the bot developers. So this is not the right place to ask details specifically about the "bot".

**Comment by keyphact** [comment]
Going to lock, you can express yourselves via the Github smiley icon :)

**Comment by elpibeninja** [comment]
great joob guys!!! thanks

**Comment by LJeremy** [comment]
We would like to take this opportunity reiterate our stance within the community:

► Our purpose lies in cracking the API and that is our sole passion only.
► We do not support third-party projects 'nor their actions. 

- /u/ChipIsTheName
