### ISSUE TITLE
Missing a few things

### ISSUE THREAD

**Issue by onlythechosen** [pkmngodev/Unknown6#71]
message LocationUpdate {
        string provider = 1; 
        uint64 timestamp_since_start = 2; 
	float altitude = 4;
        float latitude = 13;
        float longitude = 14;
        float accuracy = 21;
        uint64 location_status = 26; 
        uint64 location_type = 28; 
    }

    message SatelliteInfo {
        uint64 time_to_fix = 1;
        repeated int32 satellites_prn = 2;
        repeated float snr = 3;
        repeated float azimuth = 4;
        repeated float elevation = 5; 
        repeated bool has_almanac = 6;
        repeated bool has_ephemeris = 7;
        repeated bool used_in_fix = 8;
    }

    message SensorInfo {
        uint64 timestamp_snapshot = 1; 
        double linear_acceleration_x = 3;
        double linear_acceleration_y = 4;
        double linear_acceleration_z = 5;
        double magnetic_field_x = 6;
        double magnetic_field_y = 7;
        double magnetic_field_z = 8;
        double rotation_vector_x = 10;
        double rotation_vector_y = 11;
        double rotation_vector_z = 12;
        double gyroscope_x = 13;
        double gyroscope_y = 14;
        double gyroscope_z = 15;
        double gravity_x = 16;
        double gravity_y = 17;
        double gravity_z = 18;
        uint64 signals_status = 19; 
    }

**Comment by firebolt55439** [comment]
@onlythechosen If you want to submit changes, a pull request would be the better way to go :).

**Comment by xssc** [comment]
Make a PR

**Comment by gurupras** [comment]
This is super interesting.
From an purely educational perspective, how did you figure out the field names?

**Comment by xssc** [comment]
@gurupras his field names are just more accurate terms that are actually used for device settings, if on android you can download an app that will tell you sensor info and you can see the names.

**Comment by gurupras** [comment]
But how does one figure the names out in the first place? Not to mention the order.
I've seen from the `protoc --decode_raw` that it gives us the general outline. To me, figuring out what the fields are sounds awesome

**Comment by onlythechosen** [comment]
IIterable satellites = gpsStatus.Satellites;
                IIterator sat = satellites.Iterator();                
                int i = 0;
                while (sat.HasNext)
                {
                    GpsSatellite satellite = sat.Next().JavaCast<GpsSatellite>();
                    Console.WriteLine(satellite.Prn);
                    Console.WriteLine(satellite.Snr);
                    Console.WriteLine(satellite.Azimuth);
                    Console.WriteLine(satellite.Elevation);
                    Console.WriteLine(satellite.HasAlmanac);
                    Console.WriteLine(satellite.HasEphemeris);
                    Console.WriteLine(satellite.UsedInFix());                    
                }

sensorManager.RegisterListener(this,
                                    sensorManager.GetDefaultSensor(SensorType.Accelerometer),
                                    SensorDelay.Ui);

            sensorManager.RegisterListener(this,
                                    sensorManager.GetDefaultSensor(SensorType.MagneticField),
                                    SensorDelay.Ui);

            sensorManager.RegisterListener(this,
                                    sensorManager.GetDefaultSensor(SensorType.RotationVector),
                                    SensorDelay.Ui);

            sensorManager.RegisterListener(this,
                                    sensorManager.GetDefaultSensor(SensorType.Gravity),
                                    SensorDelay.Ui);

            sensorManager.RegisterListener(this,
                                    sensorManager.GetDefaultSensor(SensorType.Gyroscope),
                                    SensorDelay.Ui);

            sensorManager.RegisterListener(this,
                                    sensorManager.GetDefaultSensor(SensorType.LinearAcceleration),
                                    SensorDelay.Ui);

**Comment by s7092910** [comment]
I think he is more asking how did you know that these field names reflect what they actually are.

**Comment by gurupras** [comment]
Right. How do you know that the protobuf structure actually denotes *these* fields?

**Comment by tkSimon** [comment]
They figured it out by reverse engineering the code that writes the protobuf.
